[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "server"
source = "server"

[services.variables]
NODE_ENV = "production"
PORT = "${{ RAILWAY_PUBLIC_PORT }}"
DATABASE_URL = "${{ DATABASE_URL }}"
REDIS_URL = "${{ REDIS_URL }}"

[[services]]
name = "client"
source = "client"

[services.variables]
VITE_API_URL = "${{ server.RAILWAY_PUBLIC_DOMAIN }}"

[[services]]
name = "database"
source = "postgres"

[[services]]
name = "redis"
source = "redis"
