name: production
on:
  branch:
    - main
  required_reviewers:
    - your-username
  wait_timer:
    minutes: 5
  deployment_branch_policy:
    protected_branches: true
    custom_branch_policies: false
