name: Deploy to Railway

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

env:
  NODE_VERSION: '20'

jobs:
  deploy-railway:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Deploy to Railway
      run: |
        npm install -g @railway/cli
        railway login --token ${{ secrets.RAILWAY_TOKEN }}
        railway up --service ${{ secrets.RAILWAY_SERVICE }}

    - name: Run health check
      run: |
        sleep 30
        curl -f ${{ secrets.RAILWAY_URL }}/api/health || exit 1

    - name: Notify deployment
      if: success()
      run: |
        echo "Deployment to Railway successful!"
        # Add notification logic here
